server.port=3333
spring.application.name=SoundList

# URI do NeonDB
#spring.datasource.url=jdbc:postgresql://ep-morning-dust-aph8q7yo-pooler.c-7.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_hKv2uwjgTiA4&sslmode=require&channelBinding=require

# Configs do hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true